### ISSUE TITLE
Wireframe the scenario

### ISSUE THREAD

**Issue by sabman** [decision-labs/course-full-stack-geo#1]
```gherkin
Feature: App to find best place to live for me
As a user who just moved to a new city for work
I want to be able to find the best "neighbourhood" to rent and live in
So that I can have a happy life
```

```gherkin
Given I open my browser
When I navigate to https://findmyhood.com
Then I see a map of my current city with boundaries of neighbourhoods
```

- [x] show how to run postgis (geospatial database)
- [x] show how to find boundaries data (see openstreetmap wiki for tag -> go to overpass turbo API -> download data)
- [x] show how to load boundaries data into your database (search and try ways to load geojson into postgis) best way is something called `ogr2ogr` since it can handle 100s of input formats

**Comment by Osama-Sultan189** [comment]
WIP: Prototypes created, document added on spatial database and how to run POSTGIS
