### ISSUE TITLE
Chapter 1 Spatial Databases

### ISSUE THREAD

**Issue by sabman** [decision-labs/course-full-stack-geo#3]
- [x] what is a spatial database?
- [x] why do we need it?
- [x] what are some open source spatial databases?
- [x] how do I install PostGIS?
- [x] how do I load some data into it?
- [x] how do I query and ask interesting spatial questions using my database?
- [x] how do I visualise my queries and data?

**Comment by Osama-Sultan189** [comment]
1. Data Downloaded from overpass-turbo (geojson)
2. Geojson Data Loaded in postGIS using ogr2ogr
3. Query Data
4. Visualize Data
